// <auto-generated />
using System;
using MakeYourOwnPizza.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MakeYourOwnPizza.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.EmailVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerification");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Ingredients", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("stock")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("estimatedDelivery")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("paymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("totalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("userId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("userId", "isActive");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.OrderIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IngredientsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ingredientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("orderItemId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("quantity")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientsId");

                    b.HasIndex("ingredientId");

                    b.HasIndex("orderItemId");

                    b.ToTable("OrderIngredient");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("orderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("pizzaId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("quantity")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("orderId");

                    b.HasIndex("pizzaId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.OrderStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("orderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("stageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("orderId", "createdAt", "Id")
                        .IsDescending(false, true, true);

                    b.ToTable("OrderStage");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("idempotentKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("orderId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("paymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("transactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("orderId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Pizza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pizza");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("refreshToken")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("refreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.EmailVerification", b =>
                {
                    b.HasOne("MakeYourOwnPizza.Domain.Entities.User", "User")
                        .WithMany("EmailVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Order", b =>
                {
                    b.HasOne("MakeYourOwnPizza.Domain.Entities.User", "user")
                        .WithMany("orders")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.OrderIngredient", b =>
                {
                    b.HasOne("MakeYourOwnPizza.Domain.Entities.Ingredients", null)
                        .WithMany("orderIngredients")
                        .HasForeignKey("IngredientsId");

                    b.HasOne("MakeYourOwnPizza.Domain.Entities.Ingredients", "Ingredient")
                        .WithMany()
                        .HasForeignKey("ingredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakeYourOwnPizza.Domain.Entities.OrderItem", "orderItem")
                        .WithMany("orderIngredients")
                        .HasForeignKey("orderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("orderItem");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("MakeYourOwnPizza.Domain.Entities.Order", "order")
                        .WithMany("orderItems")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakeYourOwnPizza.Domain.Entities.Pizza", "pizza")
                        .WithMany()
                        .HasForeignKey("pizzaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("pizza");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.OrderStage", b =>
                {
                    b.HasOne("MakeYourOwnPizza.Domain.Entities.Order", "order")
                        .WithMany("orderStages")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Payment", b =>
                {
                    b.HasOne("MakeYourOwnPizza.Domain.Entities.Order", "order")
                        .WithMany("payments")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Ingredients", b =>
                {
                    b.Navigation("orderIngredients");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Order", b =>
                {
                    b.Navigation("orderItems");

                    b.Navigation("orderStages");

                    b.Navigation("payments");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.OrderItem", b =>
                {
                    b.Navigation("orderIngredients");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.User", b =>
                {
                    b.Navigation("EmailVerifications");

                    b.Navigation("orders");
                });
#pragma warning restore 612, 618
        }
    }
}
